name: Build Vote

on:
  # we want pull requests so we can build(test) but not push to image registry
  push:
    branches:
      - 'main'
    # only build when important files change
    paths:
      - 'vote/**'
      - '.github/workflows/call-docker-build-vote.yaml'
      - '.github/workflows/reusable-docker-build.yaml'
  pull_request:
    branches:
      - 'main'
    # only build when important files change
    paths:
      - 'vote/**'
      - '.github/workflows/call-docker-build-vote.yaml'
      - '.github/workflows/reusable-docker-build.yaml'
  schedule:
    # re-run montly to keep image fesh with upstream base images
    - cron: '0 0 1 * *'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  call-docker-build:
    permissions:
      packages: write
      pull-requests: write
    uses: ./.github/workflows/reusable-docker-build.yaml
    secrets:
      dockerhub-username: ${{ secrets.DOCKER_USERNAME }}
      dockerhub-password: ${{ secrets.DOCKER_PASSWORD }}
    with:
      context: vote
      image-names: |
        ghcr.io/${{ github.repository }}-results
        hryshchenkoihor/example-voting-app-results

  cve-scan:
    needs: call-docker-build
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.15.0
        with:
          image-ref: ${{ needs.call-docker-build.outputs.ghcr-tag }}
          exit-code: '1'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

  unit-test:
    needs: call-docker-build
    runs-on: ubuntu-latest
    steps:
      - name: Run unit test
        run: |
          docker run --rm -d --name unit-test ${{ needs.call-docker-build.outputs.ghcr-tag }}
          ls
          docker ps -a
          which curl
          curl -s localhost
