name: Build Result

on:
  # we want pull requests so we can build(test) but not push to image registry
  push:
    branches:
      - 'main'
    # only build when important files change
    paths:
      - 'result/**'
      - '.github/workflows/call-docker-build-result.yaml'
      - '.github/workflows/reusable-docker-build.yaml'
  pull_request:
    branches:
      - 'main'
    # only build when important files change
    paths:
      - 'result/**'
      - '.github/workflows/call-docker-build-result.yaml'
      - '.github/workflows/reusable-docker-build.yaml'
  schedule:
    # re-run montly to keep image fesh with upstream base images
    - cron: '0 0 1 * *'

jobs:
  call-docker-build:
    permissions:
      packages: write
      pull-requests: write
    uses: ./.github/workflows/reusable-docker-build.yaml
    secrets:
      dockerhub-username: ${{ secrets.DOCKER_USERNAME }}
      dockerhub-password: ${{ secrets.DOCKER_PASSWORD }}
    with:
      context: result
      image-names: |
        ghcr.io/${{ github.repository }}-results
        hryshchenkoihor/example-voting-app-results

  print-output:
    needs: call-docker-build
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ needs.call-docker-build.outputs.tags }}
          echo ${{ needs.call-docker-build.outputs.demo }}


  # cve-scan:
  #   needs: call-docker-build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Run Trivy vulnerability scanner
  #       uses: aquasecurity/trivy-action@master
  #       with:
  #         image-ref: ${{ needs.call-docker-build.outputs.tags }}
  #         format: 'sarif'
  #         output: 'trivy-results.sarif'
  #         severity: 'CRITICAL,HIGH'

  #     - name: Upload Trivy scan results to GitHub Security tab
  #       uses: github/codeql-action/upload-sarif@v2
  #       if: always()
  #       with:
  #         sarif_file: 'trivy-results.sarif'
  