name: Build Vote

on:
  # we want pull requests so we can build(test) but not push to image registry
  push:
    branches:
      - 'main'
    # only build when important files change
    paths:
      - 'vote/**'
      - '.github/workflows/call-docker-build-vote.yaml'
      - '.github/workflows/reusable-docker-build.yaml'
  pull_request:
    branches:
      - 'main'
    # only build when important files change
    paths:
      - 'vote/**'
      - '.github/workflows/call-docker-build-vote.yaml'
      - '.github/workflows/reusable-docker-build.yaml'
  schedule:
    # re-run montly to keep image fesh with upstream base images
    - cron: '0 0 1 * *'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  call-docker-build:
    permissions:
      packages: write
      pull-requests: write
    uses: ./.github/workflows/reusable-docker-build.yaml
    secrets:
      dockerhub-username: ${{ secrets.DOCKER_USERNAME }}
      dockerhub-password: ${{ secrets.DOCKER_PASSWORD }}
    with:
      context: vote
      image-names: |
        ghcr.io/${{ github.repository }}-results
        hryshchenkoihor/example-voting-app-results
