name: Build Result

on:
  # we want pull requests so we can build(test) but not push to image registry
  push:
    branches:
      - 'main'
    # only build when important files change
    paths:
      - 'result/**'
      - '.github/workflows/call-docker-build-result.yaml'
  pull_request:
    branches:
      - 'main'
    # only build when important files change
    paths:
      - 'result/**'
      - '.github/workflows/call-docker-build-result.yaml'
  schedule:
    # re-run montly to keep image fesh with upstream base images
    - cron: '0 0 1 * *'

jobs:
  call-docker-build:
    uses: ./.github/workflows/reusable-docker-build.yaml
    secrets:
      dockerhub-username: ${{ secrets.DOCKER_USERNAME }}
      dockerhub-password: ${{ secrets.DOCKER_PASSWORD }}
    with:
      context: result
      image-names: |
        hryshchenkoihor/example-voting-app-results
        ghcr.io/${{ github.repository }}-results
