name: Build Worker

on:
  # we want pull requests so we can build(test) but not push to image registry
  push:
    branches:
      - 'main'
    # only build when important files change
    paths:
      - 'worker/**'
      - '.github/workflows/call-docker-build-worker.yaml'
      - '.github/workflows/reusable-docker-build.yaml'
  pull_request:
    branches:
      - 'main'
    # only build when important files change
    paths:
      - 'worker/**'
      - '.github/workflows/call-docker-build-worker.yaml'
      - '.github/workflows/reusable-docker-build.yaml'
  schedule:
    # re-run monthly to keep image fresh with upstream base images
    - cron: '0 0 1 * *'

jobs:
  call-docker-build:
    permissions:
      packages: write
      pull-requests: write
    uses: ./.github/workflows/reusable-docker-build.yaml
    secrets:
      dockerhub-username: ${{ secrets.DOCKER_USERNAME }}
      dockerhub-password: ${{ secrets.DOCKER_PASSWORD }}
    with:
      context: worker
      image-names: |
        hryshchenkoihor/example-voting-app-worker
        ghcr.io/${{ github.repository }}-worker
