name: Reusable Docker Build and Push
on:
  workflow_call:
    inputs:
      dockerfile:
        description: Path to Dockerfile
        type: string
        required: true
    secrets:
      dockerhub-username:
        description: Docker Hub username
        required: true
      dockerhub-password:
        description: Docker Hub token
        required: true

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Docker Metadata action
        id: metadata
        uses: docker/metadata-action@v5.3.0
        with:
          images: |
            hryshchenkoihor/example-voting-app
            ghcr.io/${{github.repository}}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: login to Dockerhub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.dockerhub-username }}
          password: ${{ secrets.dockerhub-password }}
      - name: Docker build
        uses: docker/build-push-action@v5.1.0
        with:
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
