name: Reusable Docker Build and Push
on:
  workflow_call:
    inputs:
      context:
        description: Docker context (path) to start build from
        type: string
        required: true
      image-names:
        description: A list of the account/repo names for docker build and push to
        type: string
        required: true
    secrets:
      dockerhub-username:
        description: Docker Hub username
        required: true
      dockerhub-password:
        description: Docker Hub token
        required: true

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Docker Metadata action
        id: metadata
        uses: docker/metadata-action@v5.3.0
        with:
          images: ${{ inputs.image-names }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3.0.0
            
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: login to Dockerhub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.dockerhub-username }}
          password: ${{ secrets.dockerhub-password }}

      - name: Docker build
        uses: docker/build-push-action@v5.1.0
        with:
          context: ${{ inputs.context }}
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v3.1.0
        if: github.event_name == 'pull_request'
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Docker image tag(s) pushed:
            ```text
            ${{ steps.metadata.outputs.tags }}
            ```

            Labels added to images:
            ```text
            ${{ steps.metadata.outputs.labels }}
            ```
      
