name: Docker Build and Push
on:
  workflow_call:
    inputs:
      docker-username:
        description: "Docker Hub username"
        type: string
        required: true
      docker-password:
        description: "Docker Hub password"
        type: string
        required: true

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Login to GHCR
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: login to Dockerhub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
